-- MySQL Script generated by MySQL Workbench
-- Thu Sep 17 17:18:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `idAuthor` INT NOT NULL AUTO_INCREMENT,
  `AuthorName` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Music` (
  `idMusic` INT NOT NULL AUTO_INCREMENT,
  `idAuthor` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMusic`),
  INDEX `idAuthor_idx` (`idAuthor` ASC) VISIBLE,
  CONSTRAINT `idAuthor`
    FOREIGN KEY (`idAuthor`)
    REFERENCES `mydb`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disk` (
  `idDisk` INT NOT NULL AUTO_INCREMENT,
  `idMusic` INT NOT NULL,
  `Producer` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisk`),
  INDEX `idMusic_idx` (`idMusic` ASC) VISIBLE,
  CONSTRAINT `idMusic`
    FOREIGN KEY (`idMusic`)
    REFERENCES `mydb`.`Music` (`idMusic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Income` (
  `idIncome` INT NOT NULL,
  `idDisk` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Incomecost` INT NOT NULL,
  PRIMARY KEY (`idIncome`),
  INDEX `idDisk_idx` (`idDisk` ASC) VISIBLE,
  CONSTRAINT `idDisk`
    FOREIGN KEY (`idDisk`)
    REFERENCES `mydb`.`Disk` (`idDisk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sold` (
  `idSold` INT NOT NULL,
  `idDisk1` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Soldcost` INT NOT NULL,
  PRIMARY KEY (`idSold`),
  INDEX `idDisk_idx` (`idDisk1` ASC) VISIBLE,
  CONSTRAINT `idDisk1`
    FOREIGN KEY (`idDisk1`)
    REFERENCES `mydb`.`Disk` (`idDisk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
